apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ib-backend-pv-claim
  labels:
    app: ib
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
