apiVersion: v1
kind: Service
metadata:
  name: ib-backend
  labels:
    app: ib-backend
spec:
  ports:
  - port: 5000
  selector:
    app: ib
    tier: backend
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ib-backend
  labels:
    app: ib
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ib
        tier: backend
    spec:
      containers:
      - image: stouffcapital/com-stouffcapital-ib
        name: ib-backend
        env:
        - name: MYSQL_DATABASE
          value: ibdb
        - name: MYSQL_USER
          value: ibuser
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ib
              key: mysql-password
        - name: BASIC_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: ib
              key: backend-user
        - name: BASIC_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ib
              key: backend-password
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: ib
              key: sentry-sdk
        ports:
        - containerPort: 5000
          name: backend
        volumeMounts:
        - name: ib-backend-persistent-storage
          mountPath: /app/app/reports/data
      volumes:
      - name: ib-backend-persistent-storage
        persistentVolumeClaim:
          claimName: ib-backend-pv-claim
