apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ib-mysql-pv-claim
  namespace: ib
  labels:
    app: ib
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
